// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRzHealthcareAPIRefactor.Models;

#nullable disable

namespace PRzHealthcareAPIRefactor.Migrations
{
    [DbContext(typeof(HealthcareDbContext))]
    [Migration("20230608103223_init-commit")]
    partial class initcommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRzHealthcareAPIRefactor.Models.Account", b =>
                {
                    b.Property<int>("Acc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Acc_Id"));

                    b.Property<int>("Acc_AtyId")
                        .HasColumnType("int");

                    b.Property<string>("Acc_ContactNumber")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<DateTime>("Acc_DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Acc_Email")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)");

                    b.Property<string>("Acc_Firstname")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<DateTime>("Acc_InsertedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Acc_IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Acc_Lastname")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<string>("Acc_Login")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<DateTime>("Acc_ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Acc_Password")
                        .IsRequired()
                        .HasMaxLength(2047)
                        .HasColumnType("nvarchar(2047)");

                    b.Property<long>("Acc_Pesel")
                        .HasColumnType("bigint");

                    b.Property<int?>("Acc_PhotoId")
                        .HasColumnType("int");

                    b.Property<string>("Acc_RegistrationHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Acc_ReminderExpire")
                        .HasColumnType("datetime");

                    b.Property<string>("Acc_ReminderHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Acc_Secondname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Acc_Id");

                    b.HasIndex("Acc_AtyId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PRzHealthcareAPIRefactor.Models.AccountType", b =>
                {
                    b.Property<int>("Aty_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Aty_Id"));

                    b.Property<string>("Aty_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Aty_Id");

                    b.ToTable("AccountTypes");
                });

            modelBuilder.Entity("PRzHealthcareAPIRefactor.Models.Account", b =>
                {
                    b.HasOne("PRzHealthcareAPIRefactor.Models.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("Acc_AtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");
                });
#pragma warning restore 612, 618
        }
    }
}
